professional_background = """
## Professional Background: Rounak Zoeb

### Overview & Philosophy
A **Qualified Mechanical Engineer** who has transitioned into **Data Science** and **Generative AI**, driven by a strong passion for programming, advanced analytics, and leveraging cutting-edge AI to solve tangible, complex business problems. Currently specializing as a **Generative AI Practitioner** and **AI Solutions Architect**, focusing on designing and building robust, bespoke AI solutions that unlock significant value from data. Holds particular expertise in processing and extracting insights from complex **engineering information** and developing AI applications for **financial analytics**. Believes in combining deep technical proficiency (especially **Python**, **AI/ML**, **agentic workflows**) with bespoke business knowledge and clear communication to bridge the gap between technical intricacies and stakeholder requirements, delivering practical and impactful results.

### Current Roles & Responsibilities (Dual Directorships & Senior Data Scientist)

#### Founding Director, Digital Strategies & Services (DSS) *(July 2024 – Present)*
*   **Mission:** Co-founded DSS, a specialist technology consultancy focused on pioneering AI-driven data management solutions specifically tailored for engineering-intensive industries (Oil & Gas, Power, Metals, Mining, Agribusiness). The core mission is to move beyond off-the-shelf AI by building **custom AI Tools, advanced AI Agents, and sophisticated Agentic Workflows** that integrate seamlessly into clients' existing engineering ecosystems (ERP, EAM, CMMS, APM).
*   **Solution Leadership:** Leading the end-to-end design, architecture, development, and deployment of bespoke AI solutions. This involves processing complex, unstructured engineering information sources (PDFs, technical drawings, P&IDs, datasheets) and transforming them into valuable, structured knowledge assets.
*   **Client Engagement:** Directing client engagements from initial strategic consultation and detailed requirements gathering through to final solution implementation, validation, and continuous support, ensuring alignment with client objectives and operational realities.
*   **Key Service Offerings & Projects:**
    *   **Advanced AI-Powered Engineering Data Processing:** Architecting and implementing innovative custom AI pipelines using **agentic document processing techniques**. These pipelines intelligently extract, structure, validate, enrich, and analyze data from highly varied engineering documents, understanding intricate layouts and visual elements using **multimodal LLMs**, advanced **OCR refinement**, custom **entity extraction**, **Knowledge Graph construction** (e.g., using Neo4j), and dynamic summarization. Currently leading a significant pilot project for **CSBP (Major Australian Agribusiness & Chemical Manufacturer)** focused on AI-driven data mining from complex equipment documentation for asset management system integration.
    *   **"Doc2Dashboard" Concept:** Developing and promoting DSS's proprietary workflow concept where AI agents convert unstructured engineering data directly into interactive, dynamically generated dashboards. These dashboards provide critical, AI-generated insights into metrics such as **asset health, reliability (MTBF, MTTF), maintenance history, blueprint accuracy, equipment criticality, and cost tracking**, enabling data-driven operational decision-making.
    *   **Strategic Engineering Information Management (EIM):** Guiding clients in establishing robust enterprise-wide data standards (e.g., Class Libraries based on CFIHOS) and defining clear Information Requirements Specifications (IRS). Employing **AI agents** to assist in validating engineering document compliance against standards. Currently leading a project for **CSBP** focused on establishing a **Control Valve Digital Asset Management system**, involving complex data discovery, **AI-driven maintenance optimization**, and predictive analytics dashboard development.
*   **Technology Application:** Actively researching and applying state-of-the-art AI methodologies including advanced **RAG**, **Knowledge Graph implementation**, **multimodal LLM analysis**, **fine-tuning (LoRA, QLoRA)**, **Chain-of-Thought (CoT) reasoning**, and complex **agentic frameworks (LangChain, LlamaIndex, CrewAI, AutoGen, Pydantic, Microsoft Semantic Kernel)**. Utilizing standardized protocols like **Model Context Protocol (MCP)** and multi-agent communication frameworks like **Nvidia AgentIQ** and **Google Agent2Agent**.

#### Founding Director, STA Data *(July 2024 - Present)*
*   **Mission:** Founded STA Data to design, develop, and deploy bespoke, AI-powered applications, initially focusing on the financial services industry but with applications across various sectors.
*   **Product Leadership:** Currently leading the architecture and development of a flagship product delivering unique investment insights and recommendations. This system derives insights from proprietary trading strategies and algorithms, significantly enhanced by **custom AI** and **Large Language Model** analysis.
*   **Core Engineering:** Engineering the application's functionality involves integrating advanced financial analytics with bespoke **LLM insights** processed from diverse data sources like detailed financial reports, specialized dividend data, macroeconomic indicators, extensive historical news archives, and real-time scraped web data (e.g., from Yahoo Finance, Hot Copper) using **Python**.
*   **AI/ML Implementation:** Implementing and refining sophisticated AI/ML techniques, including **fine-tuning Large Language Models** and designing highly tailored **prompt strategies** for generating unique, context-aware stock summaries and forecasts. Also employs optimal **vector indexing strategies** and advanced **embedding models** for efficient analysis of large volumes of news articles and financial text. Developing and testing foundational **agentic AI workflows** aimed at automating financial analysis and potentially enabling future automated trading strategies.
*   **Visualization & Infrastructure:** Designing highly interactive dashboard visualizations (highlighting stock price cycles, currency pair movements with economic indicators) enhanced through **LLM-driven dynamic chart annotations** and intuitive chatbot capabilities. Establishing robust back-end infrastructure using **Python** and **AWS**, incorporating comprehensive error handling, rigorous testing via **pytest**, and evaluating scalable database solutions for dynamic financial metadata.

#### Senior Data Scientist, Newstead Connect *(April 2024 – Present)*
*   **Predictive Modeling & Solutions:** Designing, developing, and implementing fit-for-purpose predictive models and data-driven solutions using **Python**, **R**, and **SQL** for major clients (including BHP, Glencore) within Mining, Energy, and Defense sectors. Focus areas include improving project estimation, planning, scheduling, and forecasting.
*   **Generative AI Application:** Developing and managing bespoke **Generative AI** solutions, primarily incorporating **Retrieval-Augmented Generation (RAG)** pipelines, to unlock significant value from existing complex project datasets and technical engineering documentation.
*   **Workflow Automation:** Leading the automation and optimization of critical data processing workflows utilizing **VBA** and **Python**, integrated effectively with the **Microsoft Power Platform** suite, substantially reducing manual effort and enhancing data accuracy for clients.
*   **Visualization & Web Development:** Developing interactive dashboards using **Microsoft Power BI** and **TIBCO Spotfire**, alongside contributing to the development of web applications built with **React** (front-end) and **Flask (Python)** (back-end), hosted on **Azure**. Key contributions included implementing database schema automation with **Alembic** and resolving complex technical issues.
*   **Team Leadership & Recruitment:** Leading the full recruitment lifecycle for data science and developer positions and providing technical mentorship within the team. Operates effectively within **Agile/Scrum** environments.

### Relevant Past Experience

*   **BHP (Improvement Specialist & Data Analyst):** Pioneered the use of Generative AI at BHP by developing a prototype **RAG chatbot** (Python, LangChain, AWS SageMaker) for engineering document analysis, demonstrably **reducing per-document processing costs by ~90%**. Led technical development of an Estimate Benchmarking Solution, optimizing the data pipeline (**Python, SQL, VBA**) to achieve a **90% reduction in processing time**. Also automated ETL processes (**SSIS, Python**), built secure VBA applications for payroll, and developed complex dashboards (**Power BI, Spotfire**). Provided technical support and acted as SME for reporting tools.
*   **Public Transport Authority (Graduate Mechanical Engineer):** Applied **Python** and **R** for data analysis; notably developed and implemented a **Naïve Bayes Text Classification Algorithm** for automated customer feedback categorization and sentiment analysis. Used insights to recommend technology integrations.
*   **YARNZ Pty Ltd (Equities Trader & Technical Analyst):** Developed trading strategies and built backtesting applications (**JavaScript, MySQL**). Experimented with **Machine Learning** algorithms (**Python**, including **RNNs**) for stock price prediction.
*   **GM Holden (Propulsion Systems Engineering Intern):** Led root cause analysis for complex vehicle product issues using structured problem-solving and reliability data analysis. Developed **VBA** tools for process automation.

### Core Technical Proficiency Summary
Possesses advanced proficiency in **Python** and **SQL**, strong skills in **R** and **VBA**, and foundational knowledge of web technologies (**JavaScript, HTML/CSS**). Deep expertise in **AI/ML/Data Science** concepts (Generative AI, LLMs, Deep Learning, NLP, Classic ML, RL, Data Modelling, ETL, EDA). Highly experienced with core Python libraries (**Pandas, NumPy, Scikit-learn, TensorFlow, Keras**) and specialized **Agentic AI/LLM Ops** frameworks/tools (**LangChain, LlamaIndex, CrewAI, AutoGen, Pydantic, Semantic Kernel, RAG, Fine-Tuning, Prompt Engineering, Vector DBs, MCP, AgentIQ, A2A**) and platforms (**Hugging Face, OpenAI API, Google AI, Anthropic Claude**). Proficient with relational databases (**SQL Server, PostgreSQL, MySQL**), data platforms (**Snowflake, Denodo**), Knowledge Graphs (**Neo4j** - basic), cloud platforms (**AWS** - primary, Azure - basic), BI tools (**Power BI, Power Platform, Spotfire, Streamlit**), and development tools (**Git, Docker, Agile/Scrum, React.js, Flask**). Domain expertise includes **Engineering Document Analysis** and **Financial Data Analysis**.
"""

research_interests = """
## Research Interests: Rounak Zoeb

My core research interest lies in the **practical application and advancement of Artificial Intelligence (AI)**, with a strong focus on **Generative AI**, **Large Language Models (LLMs)**, and **Agentic Systems**. I am driven to develop innovative, robust, and efficient AI solutions that address complex, real-world challenges, particularly within the domains of **engineering information management** and **financial analytics**. My exploration spans foundational model capabilities, advanced application techniques, underlying technologies, and the broader AI landscape.

### Core AI Models & Agentic Systems
*   **Large Language Models (LLMs):** Deeply investigating LLM architecture (Transformers, MoE), capabilities, and limitations. Researching and applying advanced **fine-tuning techniques (LoRA, QLoRA)** for domain adaptation and task specialization. Developing sophisticated **prompt engineering strategies**, including **Chain-of-Thought (CoT)**, ReAct, and simulated reasoning, to enhance reasoning, instruction following, and output quality. Actively exploring methods to manage and effectively utilize **massive context windows** (e.g., 1M+ tokens, as seen in Llama 4 10M). Evaluating different models (GPT series, Gemini, Claude, Llama series, DeepSeek) for specific tasks.
*   **Agentic AI & Multi-Agent Systems:** Focused on designing, building, evaluating, and optimizing AI Agents and complex **Agentic Workflows**. Utilizing and extending frameworks such as **LangChain, LlamaIndex, CrewAI, AutoGen, Pydantic, and Microsoft Semantic Kernel**. Researching optimal agent architecture ("divide and conquer" vs. monolithic), tool usage, planning, and execution. Investigating advanced frameworks and protocols for **multi-agent collaboration and communication**, specifically **Nvidia AgentIQ** and **Google Agent2Agent**, to enable complex task decomposition and distributed problem-solving. Practical implementation and optimization of **Retrieval-Augmented Generation (RAG)** pipelines, including advanced techniques like contextual retrieval, hybrid search, query transformations, and reranking for improved relevance and accuracy. Exploring **Vector Search** and **quantization** methods for scalability.
*   **Model Context Protocol (MCP):** Understanding MCP's architecture and purpose for standardizing interactions between AI models and external tools/data sources (databases, APIs, file systems). Evaluating its potential use within custom applications and workflows for enhanced modularity and interoperability.
*   **AI Safety, Trust, and Reliability:** Researching mechanisms for building safer and more reliable AI systems, including **Reinforcement Learning from Human Feedback (RLHF)**, constitutional AI, safety guardrails, and adversarial training. Addressing challenges related to **bias, robustness, and interpretability**. Exploring techniques for **automated fact-checking** and source validation of LLM outputs, particularly when extracting information from documents ('LLM as a judge'). Investigating methods for robust source attribution, citation, and verification in LLM-based document processing.

### Specific Application Areas & Techniques
*   **Complex Document Parsing & Understanding:** Developing methods for automatically extracting complex information from extremely challenging documents like **engineering drawings, PDFs (scanned & native), datasheets, Excel sheets, and images**, focusing on integrating **layout information** and **text**. Evaluating and comparing state-of-the-art tools and models, including **multimodal LLMs**, specific parsing tools (**PyMuPDF4LLM, Docling, Marker, MarkItDown, MinerU, Lexoid, LlamaParse, Meta Nougat, PaddlePaddle, Donut**), cloud APIs (**Google Document AI, Amazon Textract, Azure AI Document Intelligence**), and specialized solutions (**Unstract Platform, LLM Whisperer, MiniCPM-v2.6, Deepdocdetection, ABBY FineReader API, Werk24**). Investigating **OCR-free parsing** approaches. Researching best practices for handling deterministic vs. probabilistic OCR outputs and combining OCR with LLMs/MLLMs. Exploring deterministic bounding box algorithms and image processing for segmentation and detailed analysis.
*   **Information Extraction from Engineering Documents:** Specific focus on automating the extraction of key parameters, attributes, relationships, and knowledge from technical specifications, P&IDs, datasheets, inspection reports, and work instructions common in engineering domains.
*   **Knowledge Graphs (KGs):** Investigating methods to **construct Knowledge Graphs automatically from unstructured and semi-structured text**, particularly from engineering documents, potentially using libraries like **Neo4j**. Evaluating frameworks like **Doc2KG**. Researching how KGs can be used in conjunction with LLMs to provide richer context, enhance reasoning capabilities, improve information retrieval accuracy, and connect information across multiple documents based on layout and content.
*   **Multimodal LLMs & Vision Language Models (VLMs):** Understanding the architecture and capabilities of models processing text and visual inputs (images, potentially video). Applying these to tasks like engineering drawing analysis, **Scene Text Visual Question Answering (STVQA)**, and interpreting complex diagrams. Researching the specific challenges of multimodal output generation compared to multimodal input. Investigating the relationship between VLMs and diffusion models like **Stable Diffusion**. Exploring techniques like **zoomed-in text extraction** and **line-based image segmentation** for drawings. Addressing challenges in **clock and calendar understanding (LOST IN TIME)**.
*   **AI in Financial Analysis & Portfolio Management:** Applying AI/LLMs to automate and enhance financial analysis tasks, including generating bespoke stock summaries, performing advanced sentiment analysis, developing predictive analytics models, detecting anomalies in market data or performance, and providing personalized investment insights. Specific interest in applications like **dividend stripping analysis** and exploring potential competitors and AI-driven features for financial apps. Investigating specialized financial LLMs and libraries like **FinGPT**.
*   **Structured Output Generation:** Researching and implementing best practices for forcing LLM outputs into specific, pre-defined formats (e.g., **JSON, CSV, structured text**) using techniques like prompt engineering, schema guidance, constrained decoding, function calling, and output parsing with validation (e.g., using **Pydantic**). Understanding associated risks like prompt injection and mitigation strategies.

### Underlying Technologies & Methodologies
*   **Machine Learning & Deep Learning:** Maintaining strong knowledge of fundamental ML algorithms, advanced Deep Learning architectures (**Transformers, CNNs, RNNs, LSTMs, Mixture of Experts - MoE**), and **Reinforcement Learning** concepts and algorithms (**Q-learning, Policy Gradients, Deep RL**), particularly as applied to LLM training (**RLHF**). Understanding concepts like bias-variance tradeoff and evaluation metrics.
*   **Optimization & Efficiency:** Exploring techniques like **LLM prompt caching** for reducing latency and cost in repetitive tasks. Investigating **embedding quantization** and efficient vector search methods for scalability in RAG systems. Understanding LLM **hyperparameters** and their impact. Analyzing **context limits** in LLMs and strategies for maximizing usable context.
*   **Cloud Platforms & Deployment:** Leveraging **AWS** (SageMaker, S3, EC2, Lambda) and **Azure** for training, deploying, and scaling AI models and applications. Utilizing containerization with **Docker** for environment management and simplified deployment workflows.
*   **Development Ecosystem:** Primarily using **Python** and its rich ecosystem of libraries (Pandas, NumPy, Scikit-learn, TensorFlow, etc.). Employing best practices for software development including version control with **Git** and working within **Agile/Scrum** frameworks.

### Broader AI Landscape & Future Directions
*   **Artificial General Intelligence (AGI):** Following theoretical progress and ongoing debates surrounding AGI development and implications.
*   **Robotics:** Interest in the development and application of **foundational models in physical robots** and how they intersect with language and vision models.
*   **Human Brain vs. LLMs:** Comparative analysis of information processing, architecture, learning, strengths (common sense, creativity, embodiment), and weaknesses (speed, memory, scalability) between biological and artificial intelligence.
*   **Emerging Trends:** Actively monitoring new research papers (especially from **arXiv**), model releases, benchmark results (e.g., **LM Arena**), framework updates, and practical applications discussed in industry reports, expert blogs (**Sebastian Raschka, Huyen Chip, Maarten Grootendorst**), and community forums (**Hugging Face, Y Combinator News**). Keeping track of developments from key AI research labs and companies.
"""